spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/chanxiang?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: HKZ151544a
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
jwt:
  secret: chanxiang-256-bit-secret-key-here-123456
  expiration: 7 200 000
server:
  port: 8083