spring:
  application:
    name: gateway-service
  security:
    user:
      name: guest
      password: guest
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
jwt:
  secret: chanxiang-256-bit-secret-key-here-123456
  expiration: 7 200 000