spring:
  application:
    name: auth-service
  security:
    user:
      name: guest
      password: guest
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    url: jdbc:mysql://localhost:3306/chanxiang?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: HKZ151544a
  mail:
    host: smtp.qq.com
    port: 587
    username: 3192250443@qq.com
    password: uiqeuxnclyntdecf
    properties:
      mail.smtp.starttls.enable: true
  data:
    redis:
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 100ms
jwt:
  secret: chanxiang-256-bit-secret-key-here-123456
  expiration: 86400000
server:
  port: 8081